---
- hosts: all
  roles:
          - role: "yum_configuration"
          - role: "hostname"
          - role: "software_installation"
- hosts: hadoop_name_node
  roles:
          - role: "hadoop_namenode"
- hosts: hadoop_job_tracker
  roles:
          - role: "hadoop_jobtracker"
- hosts: hadoop_data_node
  roles:
          - role: "hadoop_datanode"
- hosts: hadoop_task_tracker
  roles:
          - role: "hadoop_tasktracker"
- hosts: hadoop_client_node
  roles:
          - role: "hadoop_clientnode"
