---
# tasks file for hadoop_clientnode
- name: "Configuring core-site.xml file"
  template:
          src: "core-site.xml.j2"
          dest: "/etc/hadoop/core-site.xml"
          force: true
- name: "Configuring mapred-site.xml file"
  template:
          src: "mapred-site.xml.j2"
          dest: "/etc/hadoop/mapred-site.xml"
          force: true
